### ISSUE TITLE
Release cook 2.35

### ISSUE THREAD

**Issue by shlomif** [mdhender/cook#14]
A 2.35 release with a fixed bootstrapping procedure is needed.

**Comment by mdhender** [comment]
@shlomif , not sure what you're requesting.

**Comment by shlomif** [comment]
@mdhender : the current release of cook does not build and cannot be bootstrapped using gnu autotools. It is high time to mint a new release with a "2.35" version number and the changes in this pull req applied - https://github.com/mdhender/cook/pull/13 .

**Comment by shlomif** [comment]
@mdhender : ping

**Comment by mdhender** [comment]
Merged into master and created 2.35 tag. Thank you!

**Comment by shlomif** [comment]
On Sun, 24 Jan 2021 10:01:39 -0800
Michael D Henderson <notifications@github.com> wrote:

> Closed #14.
> 

Thanks, Michael!  ♥!


-- 

Shlomi Fish       https://www.shlomifish.org/
https://is.gd/i5eMQd - Emma Watson’s Interview for a Software Dev Job

  <rindolf> Java: because there is nothing better to do with 16 GB of RAM.
    — Freenode’s ##programming

Please reply to list if it's a mailing list post - https://shlom.in/reply .
